In [1]:
import torch

In [2]:
# (Batch , Time , Features)
# 2 sentences , 3 words , 4 features
x = torch.ones((2,3,4))
weights = torch.tensor([1.0 , 2.0 , 10.0 , 100.0]) # (4,)

scaled_x = x * weights.view(1,1,4)

print(x.shape)
print(weights.shape)
print(weights.view(1,1,4).shape)
print(scaled_x.shape)

torch.Size([2, 3, 4])
torch.Size([4])
torch.Size([1, 1, 4])
torch.Size([2, 3, 4])


In [ ]:
B,H,T,D = 2,8,10,64

# (Batch , Heads , Time , Time)
attention_weights = torch.randn(B,H,T,T)

# (Batch , Heads , Time , Dimensions)
values = torch.randn(B,H,T,D)

# PyTorch treats (B,H) as 'Batch Indices' and
# multiplies (T,T) @ (T,D) -> (T,D)
contextualized_values = attention_weights @ values

print(f"Attention Shape: {attention_weights.shape}")
print(f"Values Shape: {values.shape}")
print(f"Output Shape: {contextualized_values.shape}") # Should be (B, H, T, D)

Attn Shape: torch.Size([2, 8, 10, 10])
Values Shape: torch.Size([2, 8, 10, 64])
Output Shape: torch.Size([2, 8, 10, 64])


In [5]:
col = torch.arange(4).view(4,1)
row = torch.arange(3).view(1,3)

grid = col * row
# (4,1) stretches to (4,3)
# (1,3) stretches to (4,3)

print(col) ; print(row) ; print(grid)

tensor([[0],
        [1],
        [2],
        [3]])
tensor([[0, 1, 2]])
tensor([[0, 0, 0],
        [0, 1, 2],
        [0, 2, 4],
        [0, 3, 6]])


In [6]:
# (B,H,T,D)
x = torch.zeros((32,8,10,64))

head_bias = torch.randn(8) # (8,)

# x + head_bias crashes because
# (32,8,10,64) + (8,) dont match from the right

aligened_bias = head_bias.view(1,8,1,1) # (1,8,1,1)

result = x + aligened_bias
print(result.shape)

torch.Size([32, 8, 10, 64])


In [9]:
B,H,T,D = 32,8,10,64
Q = torch.randn(B,H,T,D)
K = torch.randn(B,H,T,D)

attention = torch.einsum('bhid,bhjd -> bhij', Q,K)

In [10]:
print(attention.shape)

torch.Size([32, 8, 10, 10])
